/**
 * Agent-Files Bootstrap Gate Test Suite
 *
 * Covers the portable-bootstrap gate that routes the AI to init skills when a root
 * agent-instruction file (CLAUDE.md / AGENTS.md) is missing:
 *
 *   - lib/agent-files-state.cjs    — shared detection + dismiss-flag + offer message
 *   - init-prompt-gate.cjs         — UserPromptSubmit handleAgentFilesGate (guidance + dismiss)
 *
 * (The PreToolUse agent-files-skill-gate.cjs router was removed with that hook; the
 *  UserPromptSubmit prompt gate + shared state lib now own all bootstrap routing.)
 *
 * Design invariants under test:
 *   - Dormant in empty projects (hasProjectContent guard) and before config is populated.
 *   - "skip init" dismisses the prompt gate for the TTL window via a shared flag.
 */

const path = require('path');
const fs = require('fs');
const { execFileSync, spawnSync } = require('child_process');
const { runHook, getHookPath, createUserPromptInput } = require('../lib/hook-runner.cjs');
const { assertEqual, assertTrue, assertContains, assertAllowed } = require('../lib/assertions.cjs');
const { createTempDir, cleanupTempDir } = require('../lib/test-utils.cjs');

const PROMPT_GATE_PATH = getHookPath('init-prompt-gate.cjs');

// Lib + its path/loader deps — cleared together so CLAUDE_PROJECT_DIR re-resolves per test.
// The config loaders capture PROJECT_DIR at module load (project-config-loader.cjs:20),
// so they read a stale project dir unless they are cleared too.
const STATE_PATH = path.resolve(__dirname, '../../lib/agent-files-state.cjs');
const CKPATHS_PATH = path.resolve(__dirname, '../../lib/ck-paths.cjs');
const CONFIG_LOADER_PATH = path.resolve(__dirname, '../../lib/project-config-loader.cjs');
const CKCONFIG_LOADER_PATH = path.resolve(__dirname, '../../lib/ck-config-loader.cjs');

// Root producer (generator) + template — used by the project-only-root tests.
const GENERATOR_PATH = path.resolve(__dirname, '../../../skills/ai-context-refresh/scripts/generate-claude-md.cjs');
const TEMPLATE_PATH = path.resolve(__dirname, '../../../skills/ai-context-refresh/references/claude-md-template.md');

const STATE_DEP_PATHS = [STATE_PATH, CKPATHS_PATH, CONFIG_LOADER_PATH, CKCONFIG_LOADER_PATH];

function freshState(tmpDir) {
    for (const p of STATE_DEP_PATHS) delete require.cache[p];
    process.env.CLAUDE_PROJECT_DIR = tmpDir;
    return require(STATE_PATH);
}

function clearStateCache() {
    for (const p of STATE_DEP_PATHS) delete require.cache[p];
}

// A project-owned root: real project content, nothing the framework generated. An existing root is
// complete as it stands: the framework's universal rules are delivered by hooks, never written into it.
const PROJECT_ONLY_FILE = '# Acme App\n\nOur internal build/deploy notes and module map.\n';
// A root generated by an older framework version: managed blocks and sections the universal hook
// delivers now.
const LEGACY_ROOT = [
    '<!-- CK:UNIVERSAL-GUIDES v7 -->',
    '',
    '<!-- CK:WORKFLOW-ROUTE-POINTER -->',
    '> **[WORKFLOW-GATE]** Workflow routing arrives from the hook.',
    '<!-- /CK:WORKFLOW-ROUTE-POINTER -->',
    '',
    '<!-- CK:CRITICAL-THINKING -->',
    '**[CRITICAL-THINKING-MINDSET]** ...',
    '<!-- /CK:CRITICAL-THINKING -->',
    '',
    '# Project',
    '',
    '<!-- SECTION:tldr -->',
    '> **Project:** Test',
    '<!-- /SECTION:tldr -->',
    '',
    '## Task Planning Rules',
    '',
    'Create a small task per change.',
    '',
    '## Git & Version-Control Discipline',
    '',
    '- Never commit unless asked.',
    '',
    '## Doc Lookup — What to Read When',
    '',
    'Project routing stays.',
    ''
].join('\n');
// Universal rules that once lived in the root and never return there.
const UNIVERSAL_MARKERS = [/CK:UNIVERSAL-GUIDES/, /CK:CRITICAL-THINKING/, /CK:AI-MISTAKE-PREVENTION/, /CK:WORKFLOW-ROUTE-POINTER/, /CK:WORKFLOW-GATE/,
    /^## Task Planning Rules/m, /^## Git & Version-Control Discipline/m, /^## Workflow Step Advancement/m, /^## Evidence-Based Reasoning/m, /^## Code Responsibility Hierarchy/m,
    /^## Continuous Improvement/m, /^## Generated Artifact Storage/m, /^## Canonical Ownership/m, /^## Project Protocol Overlays/m];

/** Populated config so isConfigPopulated() returns true (project.name + one section). */
function writePopulatedConfig(tmpDir, extra = {}) {
    const docsDir = path.join(tmpDir, 'docs');
    fs.mkdirSync(docsDir, { recursive: true });
    fs.writeFileSync(
        path.join(docsDir, 'project-config.json'),
        JSON.stringify({ project: { name: 'Test Project' }, framework: { name: 'react' }, ...extra })
    );
}

/** Temp project that passes hasProjectContent() (needs a content dir like src/). */
function createTempProjectDir() {
    const tmpDir = createTempDir();
    fs.mkdirSync(path.join(tmpDir, '.claude'));
    fs.mkdirSync(path.join(tmpDir, 'src'), { recursive: true });
    return tmpDir;
}

function withEnv(tmpDir, fn) {
    const orig = process.env.CLAUDE_PROJECT_DIR;
    process.env.CLAUDE_PROJECT_DIR = tmpDir;
    try {
        return fn();
    } finally {
        if (orig === undefined) { delete process.env.CLAUDE_PROJECT_DIR; } else { process.env.CLAUDE_PROJECT_DIR = orig; }
        clearStateCache();
    }
}

// ============================================================================
// Unit Tests: lib/agent-files-state.cjs detection + dismiss
// ============================================================================

const libTests = [
    {
        name: '[agent-files-gate] getMissingAgentFiles returns both when neither root file exists',
        fn: async () => {
            const tmpDir = createTempDir();
            try {
                withEnv(tmpDir, () => {
                    const { getMissingAgentFiles, hasMissingAgentFiles } = freshState(tmpDir);
                    const missing = getMissingAgentFiles();
                    assertEqual(missing.length, 2, 'Both CLAUDE.md and AGENTS.md missing');
                    assertEqual(missing.map(m => m.file).sort().join(','), 'AGENTS.md,CLAUDE.md', 'Correct files reported');
                    assertTrue(hasMissingAgentFiles(), 'hasMissingAgentFiles true');
                });
            } finally {
                cleanupTempDir(tmpDir);
            }
        }
    },
    {
        name: '[agent-files-gate] getMissingAgentFiles returns empty when both files present',
        fn: async () => {
            const tmpDir = createTempDir();
            try {
                // Complete fixtures (carry the sentinel): both present AND not incomplete,
                // so hasMissingAgentFiles() — which now also flags incomplete — stays false.
                // Each file gets ITS OWN surface form: CLAUDE.md inlines the protocol, AGENTS.md
                // points at the context file that carries it.
                fs.writeFileSync(path.join(tmpDir, 'CLAUDE.md'), PROJECT_ONLY_FILE);
                fs.writeFileSync(path.join(tmpDir, 'AGENTS.md'), PROJECT_ONLY_FILE);
                withEnv(tmpDir, () => {
                    const { getMissingAgentFiles, hasMissingAgentFiles } = freshState(tmpDir);
                    assertEqual(getMissingAgentFiles().length, 0, 'No missing files');
                    assertTrue(!hasMissingAgentFiles(), 'hasMissingAgentFiles false');
                });
            } finally {
                cleanupTempDir(tmpDir);
            }
        }
    },
    {
        name: '[agent-files-gate] getMissingAgentFiles reports only AGENTS.md when CLAUDE.md present',
        fn: async () => {
            const tmpDir = createTempDir();
            try {
                fs.writeFileSync(path.join(tmpDir, 'CLAUDE.md'), '# CLAUDE\n');
                withEnv(tmpDir, () => {
                    const { getMissingAgentFiles } = freshState(tmpDir);
                    const missing = getMissingAgentFiles();
                    assertEqual(missing.length, 1, 'One file missing');
                    assertEqual(missing[0].file, 'AGENTS.md', 'AGENTS.md is the missing one');
                    assertEqual(missing[0].aiRunnable, true, 'AGENTS.md route is AI-runnable');
                    assertContains(missing[0].route, 'sync-codex', 'Routes to /sync-codex');
                });
            } finally {
                cleanupTempDir(tmpDir);
            }
        }
    },
    {
        name: '[agent-files-gate] dismiss flag round-trips and reads back as dismissed',
        fn: async () => {
            const tmpDir = createTempDir();
            try {
                fs.mkdirSync(path.join(tmpDir, '.claude'));
                withEnv(tmpDir, () => {
                    const state = freshState(tmpDir);
                    assertTrue(!state.isAgentFilesDismissed(), 'Not dismissed before flag written');
                    state.writeAgentFilesDismissFlag();
                    assertTrue(state.isAgentFilesDismissed(), 'Dismissed after flag written');
                    // Flag lives under project tmp, not inside .claude (keeps framework portable)
                    assertTrue(
                        fs.existsSync(path.join(tmpDir, 'tmp', 'claude-temp', '.agent-files-dismissed')),
                        'Dismiss flag written to project tmp dir'
                    );
                });
            } finally {
                cleanupTempDir(tmpDir);
            }
        }
    },
    {
        name: '[agent-files-gate] dismiss flag past TTL reads back as NOT dismissed (expiry restores gate)',
        fn: async () => {
            const tmpDir = createTempDir();
            try {
                fs.mkdirSync(path.join(tmpDir, '.claude'));
                withEnv(tmpDir, () => {
                    const state = freshState(tmpDir);
                    state.writeAgentFilesDismissFlag();
                    assertTrue(state.isAgentFilesDismissed(), 'Fresh flag reads as dismissed (sanity)');
                    // Backdate the flag mtime just past the TTL window — the expiry branch
                    // (ageMs < DISMISS_TTL_MS === false) has no other coverage; DISMISS_TTL_MS
                    // is exported specifically to make this boundary testable without sleeping.
                    const flagPath = path.join(tmpDir, 'tmp', 'claude-temp', '.agent-files-dismissed');
                    const agedSec = (Date.now() - state.DISMISS_TTL_MS - 60_000) / 1000;
                    fs.utimesSync(flagPath, agedSec, agedSec);
                    assertTrue(!state.isAgentFilesDismissed(), 'Flag older than TTL → not dismissed (expiry branch)');
                });
            } finally {
                cleanupTempDir(tmpDir);
            }
        }
    },
    {
        name: '[agent-files-gate] isAgentFilesDismissRequest matches skip init / skip setup phrasing',
        fn: async () => {
            const tmpDir = createTempDir();
            try {
                withEnv(tmpDir, () => {
                    const { isAgentFilesDismissRequest } = freshState(tmpDir);
                    assertTrue(isAgentFilesDismissRequest('skip init'), 'matches "skip init"');
                    assertTrue(isAgentFilesDismissRequest('please skip setup for now'), 'matches "skip setup" in sentence');
                    assertTrue(isAgentFilesDismissRequest('SKIP  INIT'), 'case + whitespace tolerant');
                    assertTrue(!isAgentFilesDismissRequest('initialize the project'), 'does not match unrelated prompt');
                });
            } finally {
                cleanupTempDir(tmpDir);
            }
        }
    },
    {
        name: '[agent-files-gate] buildOfferMessage routes each missing file to its generator skill',
        fn: async () => {
            const tmpDir = createTempDir();
            try {
                withEnv(tmpDir, () => {
                    const { getMissingAgentFiles, buildOfferMessage } = freshState(tmpDir);
                    const msg = buildOfferMessage(getMissingAgentFiles());
                    assertContains(msg, '/project-init', 'Offers unified project init route');
                    assertContains(msg, '/ai-context-refresh', 'Offers root AI-context route');
                    assertContains(msg, '/sync-codex', 'Offers AGENTS.md route');
                    assertContains(msg, 'node .claude/skills/sync-codex/scripts/run-codex-sync.mjs', 'Documents standalone Codex sync fallback');
                });
            } finally {
                cleanupTempDir(tmpDir);
            }
        }
    },
    {
        name: '[agent-files-gate] buildOfferMessage offers the AGENTS.md route as AI-runnable, not user-invoked only',
        fn: async () => {
            const tmpDir = createTempDir();
            try {
                withEnv(tmpDir, () => {
                    const { getMissingAgentFiles, buildOfferMessage } = freshState(tmpDir);
                    const missing = getMissingAgentFiles();
                    const claudeEntry = missing.find(m => m.file === 'CLAUDE.md');
                    assertTrue(!!claudeEntry, 'CLAUDE.md among missing');
                    assertEqual(claudeEntry.aiRunnable, true, 'CLAUDE.md route is AI-runnable');
                    const msg = buildOfferMessage(missing);
                    assertContains(msg, 'run /ai-context-refresh', 'aiRunnable=true → "run {route}" phrasing');
                    assertContains(msg, 'run /sync-codex', 'AGENTS.md route uses "run {route}" phrasing');
                    assertTrue(!msg.includes('ask the user to run /sync-codex'), 'AGENTS.md route is no longer user-invoked only');
                    assertTrue(!msg.includes('user-invoked only'), 'the targeted-routes list no longer labels /sync-codex user-invoked only');
                    assertContains(msg, 'node .claude/skills/sync-codex/scripts/run-codex-sync.mjs', 'AGENTS.md route includes node fallback');
                });
            } finally {
                cleanupTempDir(tmpDir);
            }
        }
    }
];

// ============================================================================
// Integration Tests: init-prompt-gate.cjs handleAgentFilesGate via stdin
// ============================================================================

const promptGateIntegration = [
    {
        name: '[agent-files-gate] prompt-gate WARNS and allows an ordinary prompt when root files missing',
        fn: async () => {
            const tmpDir = createTempProjectDir();
            try {
                writePopulatedConfig(tmpDir);
                const result = await runHook(PROMPT_GATE_PATH, createUserPromptInput('add a new feature to the dashboard'), {
                    cwd: tmpDir,
                    env: { CLAUDE_PROJECT_DIR: tmpDir }
                });
                assertAllowed(result.code, 'Missing root files → warning emitted but prompt allowed');
                assertContains(result.stdout, '/project-init', 'Offer surfaces the unified project init route');
                assertContains(result.stdout, '/ai-context-refresh', 'Offer surfaces the root AI-context route');
            } finally {
                cleanupTempDir(tmpDir);
            }
        }
    },
    {
        name: '[agent-files-gate] prompt-gate "skip init" dismisses and allows (writes shared flag)',
        fn: async () => {
            const tmpDir = createTempProjectDir();
            try {
                writePopulatedConfig(tmpDir);
                const result = await runHook(PROMPT_GATE_PATH, createUserPromptInput('skip init'), {
                    cwd: tmpDir,
                    env: { CLAUDE_PROJECT_DIR: tmpDir }
                });
                assertAllowed(result.code, 'Dismiss request → allowed');
                assertTrue(
                    fs.existsSync(path.join(tmpDir, 'tmp', 'claude-temp', '.agent-files-dismissed')),
                    'Shared dismiss flag written'
                );
            } finally {
                cleanupTempDir(tmpDir);
            }
        }
    }
];

// ============================================================================
// Unit Tests: a root is complete when it exists (the gate checks existence, not content)
// ============================================================================

const existenceOnlyTests = [
    {
        name: '[agent-files-gate] a project-only root is complete: existing files are accepted as-is',
        fn: async () => {
            const tmpDir = createTempDir();
            try {
                writePopulatedConfig(tmpDir);
                fs.writeFileSync(path.join(tmpDir, 'CLAUDE.md'), PROJECT_ONLY_FILE);
                fs.writeFileSync(path.join(tmpDir, 'AGENTS.md'), PROJECT_ONLY_FILE);
                withEnv(tmpDir, () => {
                    const { getAgentFileIssues, hasMissingAgentFiles } = freshState(tmpDir);
                    assertEqual(getAgentFileIssues().length, 0, 'project-only roots raise no issue');
                    assertTrue(!hasMissingAgentFiles(), 'nothing is missing');
                });
            } finally { cleanupTempDir(tmpDir); }
        }
    },
    {
        name: '[agent-files-gate] getAgentFileIssues: present CLAUDE.md + missing AGENTS.md → one missing issue',
        fn: async () => {
            const tmpDir = createTempDir();
            try {
                writePopulatedConfig(tmpDir);
                fs.writeFileSync(path.join(tmpDir, 'CLAUDE.md'), PROJECT_ONLY_FILE);
                withEnv(tmpDir, () => {
                    const { getAgentFileIssues } = freshState(tmpDir);
                    const issues = getAgentFileIssues();
                    assertEqual(issues.length, 1, 'Only AGENTS.md is an issue');
                    assertEqual(issues[0].file, 'AGENTS.md', 'AGENTS.md missing');
                    assertEqual(issues[0].reason, 'missing', 'a present CLAUDE.md is not flagged');
                    assertEqual(issues[0].mode, 'init', 'a missing file routes to init');
                });
            } finally { cleanupTempDir(tmpDir); }
        }
    },
    {
        name: '[agent-files-gate] the state lib exports no universal-guides, sentinel or protocol-probe API',
        fn: async () => {
            const tmpDir = createTempDir();
            try {
                withEnv(tmpDir, () => {
                    const state = freshState(tmpDir);
                    for (const retired of ['hasUniversalGuides', 'isUniversalGuidesRequired', 'hasClaudeProtocol', 'hasAgentsProtocol', 'UNIVERSAL_GUIDES_VERSION', 'SENTINEL_RE', 'REQUIRED_ANCHORS', 'CK_PROTOCOL_MARKERS', 'CANONICAL_PROTOCOL_PHRASES']) {
                        assertTrue(!(retired in state), `${retired} is retired`);
                    }
                    for (const entry of state.AGENT_FILES) assertTrue(!('hasProtocol' in entry), `${entry.file} has no protocol probe`);
                });
            } finally { cleanupTempDir(tmpDir); }
        }
    },
    {
        name: '[agent-files-gate] buildOfferMessage names the missing files and their generator routes, with no opt-out or smart-merge text',
        fn: async () => {
            const tmpDir = createTempDir();
            try {
                writePopulatedConfig(tmpDir);
                withEnv(tmpDir, () => {
                    const { getAgentFileIssues, buildOfferMessage } = freshState(tmpDir);
                    const msg = buildOfferMessage(getAgentFileIssues());
                    assertContains(msg, 'CLAUDE.md missing', 'names CLAUDE.md');
                    assertContains(msg, 'AGENTS.md missing', 'names AGENTS.md');
                    assertContains(msg, '/ai-context-refresh', 'CLAUDE.md route');
                    assertContains(msg, '/sync-codex', 'AGENTS.md route');
                    for (const retired of ['requireUniversalGuides', 'smart-merge', '--mode update', 'opt out']) {
                        assertTrue(!msg.includes(retired), `offer no longer mentions ${retired}`);
                    }
                });
            } finally { cleanupTempDir(tmpDir); }
        }
    },
    {
        name: '[agent-files-gate] prompt-gate stays quiet about project-only roots',
        fn: async () => {
            const tmpDir = createTempProjectDir();
            try {
                writePopulatedConfig(tmpDir);
                fs.writeFileSync(path.join(tmpDir, 'CLAUDE.md'), PROJECT_ONLY_FILE);
                fs.writeFileSync(path.join(tmpDir, 'AGENTS.md'), PROJECT_ONLY_FILE);
                const result = await runHook(PROMPT_GATE_PATH, createUserPromptInput('add a new feature to the dashboard'), {
                    cwd: tmpDir,
                    env: { CLAUDE_PROJECT_DIR: tmpDir }
                });
                assertAllowed(result.code, 'Project-only roots → prompt allowed');
                assertTrue(!result.stdout.includes('Root agent-instruction file'), 'no root-file offer for existing roots');
            } finally { cleanupTempDir(tmpDir); }
        }
    }
];

// ============================================================================
// Generator: the root holds project information only
// ============================================================================

function runGenerator(tmpDir, ...args) {
    return execFileSync('node', [GENERATOR_PATH, ...args], {
        cwd: tmpDir,
        env: { ...process.env, CLAUDE_PROJECT_DIR: tmpDir },
        stdio: 'pipe',
        encoding: 'utf8'
    });
}

const generatorTests = [
    {
        name: '[agent-files-gate] generator init writes a project-only root: no sentinel, no managed protocol blocks, no universal section, well under 32 KiB',
        fn: async () => {
            const tmpDir = createTempDir();
            try {
                writePopulatedConfig(tmpDir);
                runGenerator(tmpDir, '--mode', 'init');
                const out = fs.readFileSync(path.join(tmpDir, 'CLAUDE.md'), 'utf-8');
                for (const marker of UNIVERSAL_MARKERS) assertTrue(!marker.test(out), `init output carries no ${marker}`);
                assertContains(out, 'Test Project', 'the project name is written');
                assertContains(out, '<!-- SECTION:tldr -->', 'generated sections are kept');
                assertTrue(Buffer.byteLength(out, 'utf8') < 32768, 'the root is under the 32 KiB host budget');
                withEnv(tmpDir, () => {
                    assertEqual(freshState(tmpDir).getAgentFileIssues().find(i => i.file === 'CLAUDE.md'), undefined, 'the gate reads the generated root as complete');
                });
            } finally { cleanupTempDir(tmpDir); }
        }
    },
    {
        name: '[agent-files-gate] generator update on a markerless project-only file leaves it byte-identical and the check accepts it',
        fn: async () => {
            const tmpDir = createTempDir();
            try {
                writePopulatedConfig(tmpDir);
                const claudeMd = path.join(tmpDir, 'CLAUDE.md');
                fs.writeFileSync(claudeMd, PROJECT_ONLY_FILE);
                runGenerator(tmpDir, '--mode', 'update');
                assertEqual(fs.readFileSync(claudeMd, 'utf-8'), PROJECT_ONLY_FILE, 'a markerless root is project-owned and untouched');
                // The read-only check exits 0 (current) for a markerless root
                let status = 0;
                try {
                    runGenerator(tmpDir, '--check');
                } catch (error) {
                    status = error.status;
                }
                assertEqual(status, 0, 'the sync preflight accepts a markerless project-owned root');
            } finally { cleanupTempDir(tmpDir); }
        }
    },
    {
        name: '[agent-files-gate] generator update strips the managed blocks of an older root, reports the legacy sections it keeps, and is idempotent',
        fn: async () => {
            const tmpDir = createTempDir();
            try {
                writePopulatedConfig(tmpDir);
                const claudeMd = path.join(tmpDir, 'CLAUDE.md');
                fs.writeFileSync(claudeMd, LEGACY_ROOT);
                const run = spawnSync('node', [GENERATOR_PATH, '--mode', 'update'], {
                    cwd: tmpDir,
                    env: { ...process.env, CLAUDE_PROJECT_DIR: tmpDir },
                    encoding: 'utf8'
                });
                assertEqual(run.status, 0, `update exits 0 (stderr: ${run.stderr})`);
                assertContains(run.stderr, 'LEGACY_UNIVERSAL_CONTENT', 'the run names the legacy sections it keeps');
                assertContains(run.stderr, '--strip-legacy-universal', 'and the flag that removes them');
                const after = fs.readFileSync(claudeMd, 'utf-8');
                // Managed blocks and the sentinel are gone
                for (const marker of [/CK:UNIVERSAL-GUIDES/, /CK:CRITICAL-THINKING/, /CK:WORKFLOW-ROUTE-POINTER/]) assertTrue(!marker.test(after), `${marker} stripped`);
                // Hand-editable sections stay
                assertContains(after, '## Task Planning Rules', 'a legacy section is kept without the flag');
                assertContains(after, 'Project routing stays.', 'project content is kept');
                // Second update is a no-op
                runGenerator(tmpDir, '--mode', 'update');
                assertEqual(fs.readFileSync(claudeMd, 'utf-8'), after, 'a second update changes nothing');
            } finally { cleanupTempDir(tmpDir); }
        }
    },
    {
        name: '[agent-files-gate] generator update --strip-legacy-universal removes the universal sections and keeps the project ones',
        fn: async () => {
            const tmpDir = createTempDir();
            try {
                writePopulatedConfig(tmpDir);
                const claudeMd = path.join(tmpDir, 'CLAUDE.md');
                fs.writeFileSync(claudeMd, LEGACY_ROOT);
                runGenerator(tmpDir, '--mode', 'update', '--strip-legacy-universal');
                const after = fs.readFileSync(claudeMd, 'utf-8');
                for (const marker of UNIVERSAL_MARKERS) assertTrue(!marker.test(after), `stripped: ${marker}`);
                assertContains(after, '## Doc Lookup — What to Read When', 'the project section stays');
                assertContains(after, 'Project routing stays.', 'its content stays');
                assertContains(after, '<!-- SECTION:tldr -->', 'generated sections stay');
                // Idempotent, and the stripped text does not come back
                runGenerator(tmpDir, '--mode', 'update', '--strip-legacy-universal');
                assertEqual(fs.readFileSync(claudeMd, 'utf-8'), after, 'stripping twice changes nothing');
                assertTrue(fs.existsSync(path.join(tmpDir, '.claude-md.backup')), 'a backup of the previous root is written');
            } finally { cleanupTempDir(tmpDir); }
        }
    },
    {
        name: '[agent-files-gate] the shipped template holds project sections only',
        fn: async () => {
            const tmpl = fs.readFileSync(TEMPLATE_PATH, 'utf-8');
            for (const marker of UNIVERSAL_MARKERS) assertTrue(!marker.test(tmpl), `template carries no ${marker}`);
            for (const section of ['tldr', 'doc-lookup', 'golden-rules', 'dev-commands', 'skill-activation']) {
                assertContains(tmpl, `<!-- SECTION:${section} -->`, `template keeps the generated ${section} section`);
            }
        }
    }
];

module.exports = {
    name: 'Agent-Files Bootstrap Gate',
    tests: [
        ...libTests,
        ...existenceOnlyTests,
        ...promptGateIntegration,
        ...generatorTests
    ]
};
