/**
 * Code-graph storage portability regression suite.
 *
 * The generated `.code-graph/.gitignore` is consumed by UTF-8-only tools such
 * as Biome. These cases protect both fresh generation and migration of files
 * previously written with the Windows locale encoding.
 */

const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const { resolvePythonCommand: findPythonCommand } = require('../lib/python-command.cjs');

const REPO_ROOT = path.resolve(__dirname, '..', '..', '..', '..');
const SCRIPTS_DIR = path.join(REPO_ROOT, '.claude', 'scripts');

function resolvePythonCommand() {
  return findPythonCommand({ cwd: REPO_ROOT, minMinor: 10 });
}

function generateStorage(root) {
  const python = resolvePythonCommand();
  const code = [
    'from pathlib import Path',
    'import sys',
    `sys.path.insert(0, ${JSON.stringify(SCRIPTS_DIR)})`,
    'from code_graph.incremental import get_db_path',
    'get_db_path(Path(sys.argv[1]))'
  ].join('\n');
  const result = spawnSync(python.command, [...python.baseArgs, '-c', code, root], {
    cwd: REPO_ROOT,
    encoding: 'utf8',
    timeout: 30000,
    windowsHide: true
  });
  assert.ifError(result.error);
  assert.equal(result.status, 0, `code-graph storage generation failed:\n${result.stderr}`);
}

function readStrictUtf8(file) {
  return new TextDecoder('utf-8', { fatal: true }).decode(fs.readFileSync(file));
}

function withTempRoot(run) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ck-code-graph-storage-'));
  try {
    run(root);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

const tests = [
  {
    name: '[code-graph-storage] fresh ignore file is strict UTF-8 with LF endings',
    fn: () => withTempRoot(root => {
      generateStorage(root);
      const content = readStrictUtf8(path.join(root, '.code-graph', '.gitignore'));
      assert.match(content, /Auto-generated by code-graph/);
      assert.match(content, /\n\*\n$/);
      assert.equal(content.includes('\r'), false);
    })
  },
  {
    name: '[code-graph-storage] malformed Windows-locale artifact self-heals',
    fn: () => withTempRoot(root => {
      const graphDir = path.join(root, '.code-graph');
      const ignoreFile = path.join(graphDir, '.gitignore');
      fs.mkdirSync(graphDir, { recursive: true });
      fs.writeFileSync(ignoreFile, Buffer.from([
        ...Buffer.from('# Auto-generated by code-graph '),
        0x97,
        ...Buffer.from(' legacy Windows artifact\r\n*\r\n')
      ]));

      generateStorage(root);

      const content = readStrictUtf8(ignoreFile);
      assert.match(content, /Auto-generated by code-graph/);
      assert.match(content, /\n\*\n$/);
      assert.equal(content.includes('\r'), false);
    })
  },
  {
    name: '[code-graph-storage] valid customized ignore file is preserved byte-for-byte',
    fn: () => withTempRoot(root => {
      const graphDir = path.join(root, '.code-graph');
      const ignoreFile = path.join(graphDir, '.gitignore');
      const customized = Buffer.from('# project-owned UTF-8 customization\n*.db\n!README.md\n', 'utf8');
      fs.mkdirSync(graphDir, { recursive: true });
      fs.writeFileSync(ignoreFile, customized);

      generateStorage(root);

      assert.deepEqual(fs.readFileSync(ignoreFile), customized);
    })
  }
];

module.exports = {
  name: 'code-graph-storage-portability',
  tests
};
