/**
 * Project Protocol Overlay Drift Test Suite
 *
 * Guards the Plane-1 cross-host carrier: the `CK:PROJECT-PROTOCOLS` block in CLAUDE.md must
 * agree with the overlay registry index (`docs/project-reference/skill-protocols-reference.md`).
 * The block is regenerated by the `/project-skill-protocol` skill on every add/update/delete —
 * an AI-run skill, not a script with a `--check` mode — so nothing else can catch a skipped
 * regeneration. A stale block is SILENTLY wrong: the registry says an overlay exists, CLAUDE.md
 * never names it, `AGENTS.md` (generated FROM CLAUDE.md) never carries it, and Codex simply
 * never learns the rule exists.
 *
 * PORTABILITY (lessons.md:13 — the bare-export failure class).
 * The index doc sits on the DEFAULT_REFERENCE_DOCS canonical floor, so session-init
 * auto-scaffolds an EMPTY one in every adopting repo, while the CK:PROJECT-PROTOCOLS block
 * exists only where someone put it. A suite gated on "index absent" would therefore FAIL in
 * every adopting repo. Gating on `registryHasRows` is what makes it correct in a bare export:
 * with zero overlays there is nothing to deliver, so there is nothing to guard.
 *
 * The gate MUST be a module-load-time `skip:` property. `run-all-tests.cjs:151-156` reads
 * `test.skip` BEFORE invoking `fn()`, so a runtime early-return inside `fn()` reports PASS
 * rather than SKIP and hides the reason.
 */

const path = require('path');
const fs = require('fs');

const REPO_ROOT = path.resolve(__dirname, '..', '..', '..', '..');
const CLAUDE_MD_PATH = path.join(REPO_ROOT, 'CLAUDE.md');
const INDEX_PATH = path.join(REPO_ROOT, 'docs', 'project-reference', 'skill-protocols-reference.md');

const BLOCK_OPEN = '<!-- CK:PROJECT-PROTOCOLS -->';
const BLOCK_CLOSE = '<!-- /CK:PROJECT-PROTOCOLS -->';
const SENTINEL = '_(none yet)_';
const NONE_MARKER = '_(none)_';
const REGISTRY_COLUMNS = 6;

const FIX = 'Fix: run /project-skill-protocol list to regenerate the CLAUDE.md CK:PROJECT-PROTOCOLS block';

// ---------------------------------------------------------------------------
// Parsers — pure, so the portability fixtures below can exercise them directly
// without touching the repo's real files.
// ---------------------------------------------------------------------------

function splitRow(line) {
    // `| a | b |` -> ['a', 'b']. Leading/trailing pipes produce empty edge cells.
    const cells = line.split('|').map((c) => c.trim());
    if (cells.length && cells[0] === '') cells.shift();
    if (cells.length && cells[cells.length - 1] === '') cells.pop();
    return cells;
}

function isSeparatorRow(cells) {
    return cells.length > 0 && cells.every((c) => /^:?-{3,}:?$/.test(c));
}

/**
 * Parse the Registry table. Returns { rows, malformed }:
 *   rows      — { name, target, scope } for every real (non-sentinel) data row
 *   malformed — { line, cellCount, text } for every data row not carrying exactly 6 cells
 * A malformed row is a defect in ANY repo, so it is reported separately from `rows` and is
 * never silently dropped.
 */
function parseRegistryRows(indexText) {
    const rows = [];
    const malformed = [];
    const lines = indexText.split(/\r?\n/);

    let inTable = false;
    let sawSeparator = false;

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const trimmed = line.trim();

        if (!trimmed.startsWith('|')) {
            // A blank line or prose ends the current table.
            if (inTable && trimmed === '') {
                inTable = false;
                sawSeparator = false;
            }
            continue;
        }

        const cells = splitRow(trimmed);

        if (!inTable) {
            // Header row: only the table whose first column is `Target` is the Registry table.
            if (cells[0] && cells[0].toLowerCase() === 'target') {
                inTable = true;
                sawSeparator = false;
            }
            continue;
        }

        if (!sawSeparator) {
            if (isSeparatorRow(cells)) sawSeparator = true;
            continue;
        }

        // Data row.
        if (cells.length !== REGISTRY_COLUMNS) {
            malformed.push({ line: i + 1, cellCount: cells.length, text: trimmed });
            continue;
        }

        const [target, scope, name] = cells;
        const isSentinel = target === SENTINEL || name === SENTINEL;
        if (isSentinel) continue;

        rows.push({ name, target, scope });
    }

    return { rows, malformed };
}

/** Extract the CK:PROJECT-PROTOCOLS block body, or null when the block is absent/unbalanced. */
function extractBlock(claudeMd) {
    const opens = claudeMd.split(BLOCK_OPEN).length - 1;
    const closes = claudeMd.split(BLOCK_CLOSE).length - 1;
    if (opens !== 1 || closes !== 1) return { opens, closes, body: null };

    const start = claudeMd.indexOf(BLOCK_OPEN) + BLOCK_OPEN.length;
    const end = claudeMd.indexOf(BLOCK_CLOSE);
    if (end < start) return { opens, closes, body: null };
    return { opens, closes, body: claudeMd.slice(start, end) };
}

/**
 * Parse `Active overlays: name (target) · name (target)` from the block body.
 * Returns [] for the `_(none)_` marker, or null when no `Active overlays:` line exists.
 */
function parseActiveOverlays(blockBody) {
    if (blockBody === null) return null;
    const match = blockBody.match(/^\s*>?\s*Active overlays:\s*(.*)$/m);
    if (!match) return null;

    const payload = match[1].trim();
    if (payload === '' || payload === NONE_MARKER) return [];

    return payload
        .split(/[·,]/)
        .map((part) => part.trim())
        .filter(Boolean)
        .map((part) => {
            const m = part.match(/^`?([^`(]+?)`?\s*\(\s*`?([^`)]+?)`?\s*\)$/);
            if (!m) return { name: part, target: null, raw: part };
            return { name: m[1].trim(), target: m[2].trim(), raw: part };
        });
}

function pairKey(entry) {
    return `${entry.name} (${entry.target})`;
}

// ---------------------------------------------------------------------------
// Module-load gate — see the PORTABILITY note above. These MUST be computed here,
// not inside fn(), so they can drive a static `skip:` property.
// ---------------------------------------------------------------------------

const indexExists = fs.existsSync(INDEX_PATH);
const indexText = indexExists ? fs.readFileSync(INDEX_PATH, 'utf8') : null;
const parsed = indexText !== null ? parseRegistryRows(indexText) : { rows: [], malformed: [] };
const registryHasRows = parsed.rows.length > 0;

const claudeMdExists = fs.existsSync(CLAUDE_MD_PATH);
const claudeMdText = claudeMdExists ? fs.readFileSync(CLAUDE_MD_PATH, 'utf8') : '';
const blockExists = claudeMdExists && claudeMdText.includes(BLOCK_OPEN);

const gateReason = !indexExists
    ? `registry index absent (${path.relative(REPO_ROOT, INDEX_PATH)}) — nothing to deliver`
    : 'registry holds no overlay rows (sentinel-only) — nothing to deliver';

function assertTrue(condition, message) {
    if (!condition) throw new Error(message);
}

const tests = [
    {
        // TC-PSP-030
        name: '[project-protocol-drift] CLAUDE.md carries exactly one CK:PROJECT-PROTOCOLS block',
        skip: !registryHasRows,
        skipReason: gateReason,
        fn: () => {
            const { opens, closes } = extractBlock(claudeMdText);
            assertTrue(
                opens === 1 && closes === 1,
                `Expected exactly one ${BLOCK_OPEN} and one ${BLOCK_CLOSE} in CLAUDE.md; ` +
                    `found ${opens} open / ${closes} close. The registry declares ` +
                    `${parsed.rows.length} overlay(s), so the block is required.\n${FIX}`
            );
        }
    },
    {
        // TC-PSP-031
        name: '[project-protocol-drift] the block sits outside every SECTION: marker region',
        skip: !registryHasRows,
        skipReason: gateReason,
        fn: () => {
            const blockStart = claudeMdText.indexOf(BLOCK_OPEN);
            assertTrue(blockStart !== -1, `CLAUDE.md is missing ${BLOCK_OPEN}.\n${FIX}`);

            // Walk SECTION open/close markers and assert the block start is inside none of them.
            const markerRe = /<!--\s*(\/?)SECTION:([a-z0-9-]+)\s*-->/gi;
            let m;
            let openAt = null;
            let openName = null;
            while ((m = markerRe.exec(claudeMdText)) !== null) {
                const isClose = m[1] === '/';
                if (!isClose) {
                    openAt = m.index;
                    openName = m[2];
                } else if (openAt !== null) {
                    const closeEnd = m.index + m[0].length;
                    assertTrue(
                        !(blockStart > openAt && blockStart < closeEnd),
                        `CK:PROJECT-PROTOCOLS sits inside <!-- SECTION:${openName} -->. ` +
                            'claude-md-init --mode update replaces SECTION bodies, so the block ' +
                            `would be silently destroyed on the next regeneration.\n${FIX}`
                    );
                    openAt = null;
                    openName = null;
                }
            }
        }
    },
    {
        // TC-PSP-032 / TC-PSP-033
        name: '[project-protocol-drift] block Active-overlays set equals the registry set',
        skip: !registryHasRows,
        skipReason: gateReason,
        fn: () => {
            const { body } = extractBlock(claudeMdText);
            const active = parseActiveOverlays(body);
            assertTrue(
                active !== null,
                `CK:PROJECT-PROTOCOLS block has no \`Active overlays:\` line.\n${FIX}`
            );

            // Order-insensitive by construction: compare as sets of `name (target)`.
            const expected = new Set(parsed.rows.map(pairKey));
            const actual = new Set(active.map(pairKey));

            const missing = [...expected].filter((k) => !actual.has(k));
            const extra = [...actual].filter((k) => !expected.has(k));

            assertTrue(
                missing.length === 0 && extra.length === 0,
                'CLAUDE.md CK:PROJECT-PROTOCOLS is out of sync with the registry index.\n' +
                    (missing.length ? `  Missing from the block: ${missing.join(', ')}\n` : '') +
                    (extra.length ? `  In the block but not the registry: ${extra.join(', ')}\n` : '') +
                    FIX
            );
        }
    },
    {
        // TC-PSP-034 — runs whenever the block exists, INCLUDING the empty-registry case,
        // which is exactly the state this repo ships in.
        name: '[project-protocol-drift] an empty registry renders Active overlays: _(none)_',
        skip: !blockExists || registryHasRows,
        skipReason: !blockExists
            ? 'CLAUDE.md carries no CK:PROJECT-PROTOCOLS block (adopting-repo shape)'
            : 'registry holds real overlay rows — covered by the set-equality test instead',
        fn: () => {
            const { body } = extractBlock(claudeMdText);
            const active = parseActiveOverlays(body);
            assertTrue(
                active !== null,
                `CK:PROJECT-PROTOCOLS block has no \`Active overlays:\` line.\n${FIX}`
            );
            assertTrue(
                active.length === 0,
                'The registry holds no overlays, but the block lists ' +
                    `${active.map((a) => a.raw).join(', ')}. It must read ` +
                    `\`Active overlays: ${NONE_MARKER}\`.\n${FIX}`
            );
        }
    },
    {
        // TC-PSP-039 — the C1 sensor. Deliberately gated ONLY on the block existing, never on
        // registryHasRows: the destructive write this guards against happens on the FIRST add,
        // i.e. from the empty state this repo ships in. Gating it on rows would leave the
        // invariant unguarded in precisely the state it has to survive.
        //
        // What it defends: the block has two parts — FIXED directive prose, and one mutable
        // `Active overlays:` line. Every other sensor here checks the mutable line. If a write
        // mode replaces the whole block body with a bare overlay list, ADDITIVE-ONLY disappears
        // from the only plane both hosts always read, /sync-codex copies the deletion into
        // AGENTS.md, and every other assertion in this file still passes. From then on an
        // overlay saying "skip step 4" is obeyed instead of refused.
        name: '[project-protocol-drift] the block retains its FIXED directive prose, not just the overlay list',
        skip: !blockExists,
        skipReason: 'CLAUDE.md carries no CK:PROJECT-PROTOCOLS block (adopting-repo shape)',
        fn: () => {
            const { body } = extractBlock(claudeMdText);
            const required = [
                ['ADDITIVE ONLY', 'the additive-only invariant'],
                ['NEVER replaces', 'the non-replacement clause'],
                ['never against the skill', 'the precedence-ranks-overlays-not-skills clarifier'],
                ['authority escalation', 'the brief-not-authority carve-out'],
                ['WORKFLOW-GATE', 'the WORKFLOW-GATE carve-out'],
                ['git discipline', 'the git-discipline carve-out'],
                ['NEVER resolve silently', 'the contradiction-goes-to-the-user rule']
            ];
            const lost = required.filter(([needle]) => !body.includes(needle));
            assertTrue(
                lost.length === 0,
                'The CK:PROJECT-PROTOCOLS block lost FIXED framework prose: ' +
                    lost.map(([needle, what]) => `${what} ("${needle}")`).join('; ') +
                    '.\nOnly the `Active overlays:` line is mutable — the directive prose above it is ' +
                    'reproduced byte-for-byte by every write mode. See references/registry.md ' +
                    '§ "The block has one mutable line".'
            );
        }
    },
    {
        // TC-PSP-035 — always on. Pure-parser fixture: an absent/unreadable index resolves to
        // EMPTY, never to "broken". Guards the bare-export path without touching the repo.
        name: '[project-protocol-drift] an absent registry resolves to EMPTY, never to an error',
        fn: () => {
            const { rows, malformed } = parseRegistryRows('');
            assertTrue(rows.length === 0, 'An empty index must yield zero overlay rows');
            assertTrue(malformed.length === 0, 'An empty index must yield zero malformed rows');

            // And the gate derived from it must be "skip", not "fail".
            const wouldSkip = rows.length === 0;
            assertTrue(wouldSkip, 'Zero rows must gate the delivery assertions off, not fail them');
        }
    },
    {
        // TC-PSP-036 — always on, regardless of registryHasRows: a malformed table is a defect
        // in ANY repo, and silently ignoring the row is how an overlay goes missing unnoticed.
        name: '[project-protocol-drift] a registry data row missing a column is reported, never ignored',
        fn: () => {
            const fixture = [
                '## Registry',
                '',
                '| Target | Scope | Name | Description | Updated | Body |',
                '| --- | --- | --- | --- | --- | --- |',
                '| plan | exact | ctx | Use when planning. | 2026-08-17 | [ctx.md](../project-protocols/ctx.md) |',
                '| *-review | glob | ev | Use when reviewing. | 2026-08-17 |',
                ''
            ].join('\n');

            const { rows, malformed } = parseRegistryRows(fixture);
            assertTrue(rows.length === 1, `Expected 1 well-formed row, got ${rows.length}`);
            assertTrue(malformed.length === 1, `Expected 1 malformed row, got ${malformed.length}`);
            assertTrue(
                malformed[0].cellCount === 5,
                `Malformed row must report its actual cell count; got ${malformed[0].cellCount}`
            );

            // The real index must itself be well-formed.
            assertTrue(
                parsed.malformed.length === 0,
                'Malformed row(s) in docs/project-reference/skill-protocols-reference.md:\n' +
                    parsed.malformed
                        .map((r) => `  line ${r.line}: ${r.cellCount} cell(s) — ${r.text}`)
                        .join('\n') +
                    `\nEvery data row needs exactly ${REGISTRY_COLUMNS} columns.\n${FIX}`
            );
        }
    },
    {
        // TC-PSP-037 — always on. The adopting-repo shape: session-init auto-scaffolds a
        // sentinel-only index, and CLAUDE.md carries no block. This MUST resolve to skip.
        name: '[project-protocol-drift] adopting-repo shape (sentinel index + no block) gates off, never fails',
        fn: () => {
            const scaffolded = [
                '## Registry',
                '',
                '| Target       | Scope | Name         | Description                  | Updated | Body |',
                '| ------------ | ----- | ------------ | ---------------------------- | ------- | ---- |',
                '| _(none yet)_ | —     | _(none yet)_ | Run `/project-skill-protocol add …` to create the first overlay. | —       | —    |',
                ''
            ].join('\n');

            const { rows, malformed } = parseRegistryRows(scaffolded);
            assertTrue(rows.length === 0, 'The sentinel row must never count as an overlay');
            assertTrue(malformed.length === 0, 'The scaffolded sentinel row must parse as well-formed');

            const bareClaudeMd = '# Some Project\n\nNo overlay block here.\n';
            const { opens, body } = extractBlock(bareClaudeMd);
            assertTrue(opens === 0, 'Fixture must have no block');
            assertTrue(body === null, 'An absent block must extract as null, not throw');

            // Both gates off => zero delivery assertions run => a bare export cannot fail.
            assertTrue(rows.length === 0 && opens === 0, 'Adopting-repo shape must gate every assertion off');
        }
    },
    {
        // TC-PSP-038 — the gate must be a STATIC property, because run-all-tests.cjs reads
        // test.skip before calling fn(). A runtime early-return would report PASS, not SKIP.
        name: '[project-protocol-drift] every gated test exposes a static boolean skip at module load',
        fn: () => {
            const gated = tests.filter((t) => Object.prototype.hasOwnProperty.call(t, 'skip'));
            assertTrue(gated.length > 0, 'At least one test must be gated (non-vacuous)');
            for (const t of gated) {
                assertTrue(
                    typeof t.skip === 'boolean',
                    `${t.name}: skip must be a boolean computed at module load, got ${typeof t.skip}`
                );
                assertTrue(
                    typeof t.skipReason === 'string' && t.skipReason.length > 0,
                    `${t.name}: a gated test must state WHY it skipped`
                );
            }
        }
    }
];

module.exports = {
    name: 'project-protocol-drift',
    tests,
    // Exported for reuse and for direct unit-testing of the parsers.
    parseRegistryRows,
    parseActiveOverlays,
    extractBlock
};
